BOTAN_DIR := $(call select_from_ports,botan)
BOTAN_SRC_DIR := $(BOTAN_DIR)/src/lib/botan/src/lib
$(warning BOTAN_SRC_DIR=$(BOTAN_SRC_DIR))

SHARED_LIB = yes

include $(REP_DIR)/lib/import/import-botan.mk

LIBS += stdcxx

# We really want to use maes or mssse3 instread of table lookup aes due to side channels.
CC_OPT += -maes -mpclmul -mssse3 -msse2 -mavx2

SRC_C = stream/rc4/rc4.cpp \
				stream/stream_cipher.cpp \
				stream/chacha/chacha.cpp \
				stream/ctr/ctr.cpp \
				stream/ofb/ofb.cpp \
				stream/salsa20/salsa20.cpp \
				utils/cpuid.cpp \
				utils/datastor/datastor.cpp \
				utils/calendar.cpp \
				utils/locking_allocator/locking_allocator.cpp \
				utils/os_utils.cpp \
				utils/read_cfg.cpp \
				utils/parsing.cpp \
				utils/filesystem.cpp \
				utils/zero_mem.cpp \
				utils/http_util/http_util.cpp \
				utils/charset.cpp \
				utils/data_src.cpp \
				utils/version.cpp \
				utils/assert.cpp \
				ffi/ffi.cpp \
				filters/pipe_rw.cpp \
				filters/filter.cpp \
				filters/buf_filt.cpp \
				filters/threaded_fork.cpp \
				filters/pipe.cpp \
				filters/comp_filter.cpp \
				filters/basefilt.cpp \
				filters/secqueue.cpp \
				filters/algo_filt.cpp \
				filters/transform_filter.cpp \
				filters/codec_filt/hex_filt.cpp \
				filters/codec_filt/b64_filt.cpp \
				filters/key_filt.cpp \
				filters/fd_unix/fd_unix.cpp \
				filters/data_snk.cpp \
				filters/out_buf.cpp \
				filters/pipe_io.cpp \
				compression/compression.cpp \
				cert/cvc/asn1_eac_tm.cpp \
				cert/cvc/cvc_ado.cpp \
				cert/cvc/asn1_eac_str.cpp \
				cert/cvc/cvc_req.cpp \
				cert/cvc/signed_obj.cpp \
				cert/cvc/cvc_self.cpp \
				cert/cvc/cvc_cert.cpp \
				cert/cvc/ecdsa_sig.cpp \
				cert/x509/x509cert.cpp \
				cert/x509/crl_ent.cpp \
				cert/x509/key_constraint.cpp \
				cert/x509/x509_ext.cpp \
				cert/x509/x509_ca.cpp \
				cert/x509/ocsp_types.cpp \
				cert/x509/ocsp.cpp \
				cert/x509/x509_obj.cpp \
				cert/x509/x509path.cpp \
				cert/x509/x509_crl.cpp \
				cert/x509/pkcs10.cpp \
				cert/x509/x509self.cpp \
				cert/x509/certstor.cpp \
				cert/x509/x509opt.cpp \
				entropy/entropy_srcs.cpp \
				entropy/hres_timer/hres_timer.cpp \
				entropy/dev_random/dev_random.cpp \
				kdf/prf_x942/prf_x942.cpp \
				kdf/kdf.cpp \
				kdf/hkdf/hkdf.cpp \
				kdf/prf_tls/prf_tls.cpp \
				kdf/kdf1/kdf1.cpp \
				kdf/kdf2/kdf2.cpp \
				misc/pbes2/pbes2.cpp \
				misc/aont/package.cpp \
				misc/openpgp/openpgp.cpp \
				misc/pem/pem.cpp \
				misc/fpe_fe1/fpe_fe1.cpp \
				misc/srp6/srp6.cpp \
				misc/srp6/srp6_files.cpp \
				misc/benchmark/benchmark.cpp \
				misc/tss/tss.cpp \
				misc/cryptobox/cryptobox.cpp \
				misc/rfc3394/rfc3394.cpp \
				base/scan_name.cpp \
				base/init.cpp \
				base/transform.cpp \
				base/symkey.cpp \
				hash/par_hash/par_hash.cpp \
				hash/comb4p/comb4p.cpp \
				hash/sha1/sha160.cpp \
				hash/keccak/keccak.cpp \
				hash/checksum/adler32/adler32.cpp \
				hash/checksum/crc32/crc32.cpp \
				hash/checksum/crc24/crc24.cpp \
				hash/tiger/tig_tab.cpp \
				hash/tiger/tiger.cpp \
				hash/mdx_hash/mdx_hash.cpp \
				hash/rmd160/rmd160.cpp \
				hash/gost_3411/gost_3411.cpp \
				hash/whirlpool/whrl_tab.cpp \
				hash/whirlpool/whirlpool.cpp \
				hash/sha2_64/sha2_64.cpp \
				hash/sha2_32/sha2_32.cpp \
				hash/hash.cpp \
				hash/sha1_sse2/sha1_sse2.cpp \
				hash/has160/has160.cpp \
				hash/md2/md2.cpp \
				hash/rmd128/rmd128.cpp \
				hash/md5/md5.cpp \
				hash/md4/md4.cpp \
				hash/skein/skein_512.cpp \
				tls/tls_handshake_state.cpp \
				tls/tls_client.cpp \
				tls/tls_handshake_hash.cpp \
				tls/tls_session.cpp \
				tls/tls_server.cpp \
				tls/msg_certificate.cpp \
				tls/tls_heartbeats.cpp \
				tls/msg_client_hello.cpp \
				tls/msg_finished.cpp \
				tls/tls_session_manager_memory.cpp \
				tls/tls_channel.cpp \
				tls/tls_handshake_io.cpp \
				tls/msg_session_ticket.cpp \
				tls/tls_alert.cpp \
				tls/tls_policy.cpp \
				tls/tls_session_key.cpp \
				tls/msg_server_hello.cpp \
				tls/tls_ciphersuite.cpp \
				tls/msg_cert_req.cpp \
				tls/credentials_manager.cpp \
				tls/tls_record.cpp \
				tls/tls_version.cpp \
				tls/tls_blocking.cpp \
				tls/msg_client_kex.cpp \
				tls/tls_suite_info.cpp \
				tls/msg_server_kex.cpp \
				tls/tls_extensions.cpp \
				tls/msg_hello_verify.cpp \
				tls/msg_cert_verify.cpp \
				modes/ecb/ecb.cpp \
				modes/xts/xts.cpp \
				modes/cbc/cbc.cpp \
				modes/mode_pad/mode_pad.cpp \
				modes/cipher_mode.cpp \
				modes/aead/chacha20poly1305/chacha20poly1305.cpp \
				modes/aead/ocb/ocb.cpp \
				modes/aead/aead.cpp \
				modes/aead/ccm/ccm.cpp \
				modes/aead/gcm/clmul/clmul.cpp \
				modes/aead/gcm/gcm.cpp \
				modes/aead/eax/eax.cpp \
				modes/aead/siv/siv.cpp \
				modes/cfb/cfb.cpp \
				pubkey/ecc_key/ecc_key.cpp \
				pubkey/dl_group/named.cpp \
				pubkey/dl_group/dl_group.cpp \
				pubkey/pk_keys.cpp \
				pubkey/dlies/dlies.cpp \
				pubkey/x509_key.cpp \
				pubkey/if_algo/if_algo.cpp \
				pubkey/ecdsa/ecdsa.cpp \
				pubkey/nr/nr.cpp \
				pubkey/pubkey.cpp \
				pubkey/workfactor.cpp \
				pubkey/gost_3410/gost_3410.cpp \
				pubkey/ecdh/ecdh.cpp \
				pubkey/ec_group/named.cpp \
				pubkey/ec_group/ec_group.cpp \
				pubkey/elgamal/elgamal.cpp \
				pubkey/dsa/dsa.cpp \
				pubkey/pkcs8.cpp \
				pubkey/curve25519/donna.cpp \
				pubkey/curve25519/curve25519.cpp \
				pubkey/dl_algo/dl_algo.cpp \
				pubkey/keypair/keypair.cpp \
				pubkey/blinding.cpp \
				pubkey/rfc6979/rfc6979.cpp \
				pubkey/pk_ops.cpp \
				pubkey/rsa/rsa.cpp \
				pubkey/dh/dh.cpp \
				pubkey/mceies/mceies.cpp \
				pubkey/mce/polyn_gf2m.cpp \
				pubkey/mce/mceliece_key.cpp \
				pubkey/mce/gf2m_rootfind_dcmp.cpp \
				pubkey/mce/workfactor.cpp \
				pubkey/mce/mce_kem.cpp \
				pubkey/mce/mceliece.cpp \
				pubkey/mce/gf2m_small_m.cpp \
				pubkey/mce/code_based_key_gen.cpp \
				pubkey/mce/goppa_code.cpp \
				pubkey/pk_algs.cpp \
				pubkey/rw/rw.cpp \
				pk_pad/emsa_x931/emsa_x931.cpp \
				pk_pad/emsa.cpp \
				pk_pad/hash_id/hash_id.cpp \
				pk_pad/eme_raw/eme_raw.cpp \
				pk_pad/emsa_raw/emsa_raw.cpp \
				pk_pad/emsa1/emsa1.cpp \
				pk_pad/mgf1/mgf1.cpp \
				pk_pad/eme_pkcs1/eme_pkcs.cpp \
				pk_pad/emsa1_bsi/emsa1_bsi.cpp \
				pk_pad/emsa_pssr/pssr.cpp \
				pk_pad/emsa_pkcs1/emsa_pkcs1.cpp \
				pk_pad/eme.cpp \
				pk_pad/eme_oaep/oaep.cpp \
				pbkdf/pbkdf.cpp \
				pbkdf/pbkdf1/pbkdf1.cpp \
				pbkdf/pbkdf2/pbkdf2.cpp \
				rng/hmac_rng/hmac_rng.cpp \
				rng/system_rng/system_rng.cpp \
				rng/hmac_drbg/hmac_drbg.cpp \
				rng/x931_rng/x931_rng.cpp \
				rng/rng.cpp \
				passhash/bcrypt/bcrypt.cpp \
				passhash/passhash9/passhash9.cpp \
				math/mp/mp_monty.cpp \
				math/mp/mp_mulop.cpp \
				math/mp/mp_misc.cpp \
				math/mp/mp_shift.cpp \
				math/mp/mp_karat.cpp \
				math/mp/mp_asm.cpp \
				math/mp/mp_comba.cpp \
				math/bigint/big_code.cpp \
				math/bigint/big_rand.cpp \
				math/bigint/big_ops3.cpp \
				math/bigint/divide.cpp \
				math/bigint/bigint.cpp \
				math/bigint/big_ops2.cpp \
				math/bigint/big_io.cpp \
				math/numbertheory/make_prm.cpp \
				math/numbertheory/pow_mod.cpp \
				math/numbertheory/numthry.cpp \
				math/numbertheory/mp_numth.cpp \
				math/numbertheory/primes.cpp \
				math/numbertheory/ressol.cpp \
				math/numbertheory/dsa_gen.cpp \
				math/numbertheory/reducer.cpp \
				math/numbertheory/powm_mnt.cpp \
				math/numbertheory/jacobi.cpp \
				math/numbertheory/powm_fw.cpp \
				math/ec_gfp/curve_gfp.cpp \
				math/ec_gfp/curve_nistp.cpp \
				math/ec_gfp/point_gfp.cpp \
				codec/base64/base64.cpp \
				codec/hex/hex.cpp \
				asn1/asn1_attribute.cpp \
				asn1/x509_dn.cpp \
				asn1/asn1_str.cpp \
				asn1/asn1_time.cpp \
				asn1/der_enc.cpp \
				asn1/ber_dec.cpp \
				asn1/alg_id.cpp \
				asn1/asn1_obj.cpp \
				asn1/oid_lookup/default.cpp \
				asn1/oid_lookup/oids.cpp \
				asn1/asn1_oid.cpp \
				asn1/asn1_alt_name.cpp \
				mac/mac.cpp \
				mac/hmac/hmac.cpp \
				mac/siphash/siphash.cpp \
				mac/cbc_mac/cbc_mac.cpp \
				mac/poly1305/poly1305.cpp \
				mac/x919_mac/x919_mac.cpp \
				mac/cmac/cmac.cpp \
				block/tea/tea.cpp \
				block/gost_28147/gost_28147.cpp \
				block/seed/seed_tab.cpp \
				block/seed/seed.cpp \
				block/cast/cast256.cpp \
				block/cast/cast128.cpp \
				block/serpent_simd/serp_simd.cpp \
				block/misty1/misty1.cpp \
				block/xtea/xtea.cpp \
				block/blowfish/blowfish.cpp \
				block/blowfish/blfs_tab.cpp \
				block/cascade/cascade.cpp \
				block/lion/lion.cpp \
				block/serpent/serpent.cpp \
				block/safer/safer_sk.cpp \
				block/rc2/rc2.cpp \
				block/idea_sse2/idea_sse2.cpp \
				block/mars/mars.cpp \
				block/twofish/twofish.cpp \
				block/twofish/two_tab.cpp \
				block/threefish_avx2/threefish_avx2.cpp \
				block/aes/aes.cpp \
				block/aes_ni/aes_ni.cpp \
				block/aes_ssse3/aes_ssse3.cpp \
				block/camellia/camellia.cpp \
				block/rc5/rc5.cpp \
				block/idea/idea.cpp \
				block/threefish/threefish.cpp \
				block/noekeon_simd/noekeon_simd.cpp \
				block/kasumi/kasumi.cpp \
				block/des/des.cpp \
				block/des/des_tab.cpp \
				block/des/desx.cpp \
				block/xtea_simd/xtea_simd.cpp \
				block/block_cipher.cpp \
				block/rc6/rc6.cpp \
				block/noekeon/noekeon.cpp

INC_DIR += $(BOTAN_DIR)/include \
					 $(REP_DIR)/include

vpath %.cpp $(BOTAN_SRC_DIR)
